language: python
python:
  - "2.7"
install: pip install -r requirements-dev.txt
script:  PYTHONPATH=`pwd` py.test --cov=gioland tests
after_success: coveralls
notifications:
  email:
    recipients:
      - purepython@eaudeweb.ro
