version: '3'

services:

  gioland:
    image: eeacms/gioland
    container_name: gioland
    ports:
      - '5000:5000'
    volumes:
      - ./docs:/gioland/docs
      - ./instance:/gioland/instance
    env_file: .env

  apache:
    image: eeacms/apache
    container_name: apache
    ports:
      - '80:80'
    volumes:
      - ./docker/virtual-host.conf:/usr/local/apache2/conf/extra/vh-my-app.conf
      - ./docs:/gioland/docs
