version: '2'

services:
  gioland:
    build:
      context: .
    container_name: gioland
    env_file: .env
    command: python manage.py runcherrypy -p 5000 -H 0.0.0.0
    ports:
      - '5000:5000'
  server:
    image: httpd
    expose:
      - '443'
    ports:
      - '443:443'
    cap_drop:
      - ALL
    cap_add:
      - NET_BIND_SERVICE
      - SETUID
      - SETGID
    volumes:
      - /home/dianaboiangiu/Desktop/gioland_docker/gioland/docs:/gioland/docs
    environment:
      SERVER_NAME: localhost
    links:
      - gioland:gioland
