version: '2'

services:

  gioland:
    image: eeacms/gioland
    container_name: gioland
    ports:
      - '5000:5000'
    volumes:
      - ./docs:/gioland/docs
    env_file: .env

  apache:
    image: eeacms/apache
    container_name: apache
    ports:
      - '80:80'
    volumes:
      - ./conf.d/virtual-host.conf:/usr/local/apache2/conf/extra/vh-my-app.conf
      - ./docs:/gioland/docs
    links:
      - gioland:gioland
